### ISSUE TITLE
QR-code is not loaded and fatal error in /var/log/httpd/error_log

### ISSUE THREAD

**Issue by TomashKhamlai** [magento/magespecialist_TwoFactorAuth#7]
This worked a few weeks ago but it is broken now.

**PHP information:**
```
PHP 7.0.27 (cli) (built: Jan  2 2018 12:38:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans
```
**error_log:**
```[Fri Feb 16 09:19:56.282656 2018] [:error] [pid 28223] [client 10.234.128.175:22397] PHP Fatal error:  Uncaught Error: Class 'Endroid\\QrCode\\QrCode' not found in /var/www/html/tkhamlai/2fa/app/code/MSP/TwoFactorAuth/Model/Provider/Engine/Google.php:157\nStack trace:\n#0 /var/www/html/tkhamlai/2fa/app/code/MSP/TwoFactorAuth/Controller/Adminhtml/Google/Qr.php(88): MSP\\TwoFactorAuth\\Model\\Provider\\Engine\\Google->getQrCodeAsPng(Object(Magento\\User\\Model\\User\\Interceptor))\n#1 /var/www/html/tkhamlai/2fa/generated/code/MSP/TwoFactorAuth/Controller/Adminhtml/Google/Qr/Interceptor.php(24): MSP\\TwoFactorAuth\\Controller\\Adminhtml\\Google\\Qr->execute()\n#2 /var/www/html/tkhamlai/2fa/lib/internal/Magento/Framework/App/Action/Action.php(107): MSP\\TwoFactorAuth\\Controller\\Adminhtml\\Google\\Qr\\Interceptor->execute()\n#3 /var/www/html/tkhamlai/2fa/app/code/Magento/Backend/App/AbstractAction.php(229): Magento\\Framework\\App\\Action\\Action->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#4 /var/www/html/tkhamlai/2fa/app/code/MSP/TwoFactorAuth/Controller/Adminhtml/AbstractAction.php(13): Magento\\Backend\\App\\AbstractAction->dispatch in /var/www/html/tkhamlai/2fa/app/code/MSP/TwoFactorAuth/Model/Provider/Engine/Google.php on line 157, referer: https://tsg.dev.magento.com/tkhamlai/2fa/admin/msp_twofactorauth/google/configure/key/647672bfe2df38bfc81a232e50ad05c0bc112a09eef321f7aabbabef970d35cf/```

**Screenshot:**
![problem](https://user-images.githubusercontent.com/11827230/36302159-1bcddaa2-1310-11e8-8956-597ba4dad855.png)

**Comment by TomashKhamlai** [comment]
`composer require msp/recaptcha` modifies the main `composer.json`
These changes to composer.json should be added manually if you cloned the module from GitHub.
Non-issue.
